services:
  activemq:
    image: alfresco/alfresco-activemq:6.2-jre17-rockylinux8
    container_name: activemq
    ports:
      - "61616:61616" # OpenWire
      - "8161:8161"   # Web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    container_name: toxiproxy
    ports:
      - "8474:8474"   # Toxiproxy API
      - "8666:8666"   # Proxy port for ActiveMQ